name: Test Ebook Translator
run-name: 'Test Ebook Translator: ${{ github.ref_name }}'

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libegl1 libopengl0 libxcb-cursor0
          sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin
      - name: Test with calibre-debug
        run: |
          export CALIBRE_OVERRIDE_LANG=en QT_QPA_PLATFORM=offscreen
          calibre-customize -b .; calibre-debug test.py
